[package]
name = "ffmpeg"
version = "0.0.1"
edition = "2021"


[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
serde_json = { version = "1.0.125" }
reqwest = { version = "0.12.7", features = [] }
zip = "2.2.0"
rayon = "1.10.0"
futures = "0.3.30"